### ISSUE TITLE
Setting to hide the "Back to overview" button

### ISSUE THREAD

**Issue by MaiklT** [40fingers/Open-Content-Image-Gallery#14]
It should be possible to hide the "Back to overview" button, or to have a setting that only displays the details page of a specific album (like Ventrian SimpleGallery).

**Comment by Timo-Breumelhof** [comment]
@MaiklT you can currently do this like this:

Make the gallery module hidden or place it on another page (centrally).
Place the "Picture List" template using data of the existing Gallery module.
Enter the OC Filter page and filter by Gallery Title:

![image](https://github.com/40fingers/Open-Content-Image-Gallery/assets/8999382/a705ad4f-66ec-4d08-aa8d-7967ff7ca7ac)

This will only show the images from that gallery and no back button.

HTH

**Comment by MaiklT** [comment]
Thank you Timo, that nearly works except for the first album created. All the others are fine.

**Comment by Timo-Breumelhof** [comment]
Hmm, that's weird.. I'll look at the raw data..

**Comment by Timo-Breumelhof** [comment]
Fixed, for some reason the first gallery did not have an ID

**Comment by MaiklT** [comment]
Hi Timo,

 

The sites work fine after the move to  the new server.

 

Could you please allow the full CK Editor tool bar on the sport-software site (on the kinderreich site it is OK), and the tags/attributes I sent you earlier on both sites?

 

Anyway, I have moved everything, so we can start changing the DNS entries. Could you please tell me the values for the A- (and perhaps AAAA-) entries?

 

Sport-Software does not need your email service, this will be done by someone else.

 

For Kinderreich, we need the email address ***@***.*** ***@***.***> , with the alias ***@***.*** ***@***.***> . I’ll send you the password on Skype.

 

Merry Christmas and thank you!

Michael

 

Von: Timo Breumelhof ***@***.***> 
Gesendet: Freitag, 22. Dezember 2023 17:16
An: 40fingers/Open-Content-Image-Gallery ***@***.***>
Cc: Michael Tobisch ***@***.***>; Mention ***@***.***>
Betreff: Re: [40fingers/Open-Content-Image-Gallery] Setting to hide the "Back to overview" button (Issue #14)

 

Fixed, for some reason the first gallery did not have an ID
